services:
  pocketcard-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5225:5225"
    env_file:
      - .env
    volumes:
      - pocketcard-db:/app/data
    networks:
      - pocketcard-network
    restart: unless-stopped

volumes:
  pocketcard-db:
    driver: local

networks:
  pocketcard-network:
    driver: bridge